"""initial schema - six canonical tables"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '0be1fd7c286d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('LAB_TECHNICIAN', 'APPROVING_OFFICER', 'ADMIN', name='userrole', native_enum=False, length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_email', sa.String(length=320), nullable=True),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'TRANSITION', 'UPLOAD', 'LOGIN', 'LOGOUT', 'DENIED', name='auditaction', native_enum=False, length=16), nullable=False),
    sa.Column('action_detail', sa.String(length=64), nullable=False),
    sa.Column('object_ref', sa.String(length=80), nullable=True),
    sa.Column('source_ip', sa.String(length=64), nullable=True),
    sa.Column('detail_json', sa.Text(), nullable=True),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.Column('row_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action_detail'), 'audit_log', ['action_detail'], unique=False)
    op.create_index(op.f('ix_audit_log_actor_id'), 'audit_log', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_log_at'), 'audit_log', ['at'], unique=False)
    op.create_index(op.f('ix_audit_log_object_ref'), 'audit_log', ['object_ref'], unique=False)
    op.create_table('instruments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('manufacturer', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('serial_number', sa.Text(), nullable=False),
    sa.Column('accuracy_class', sa.Enum('I', 'II', 'III', 'IIII', name='accuracyclassenum', native_enum=False, length=8), nullable=False),
    sa.Column('max_capacity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('min_capacity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('verification_scale_interval', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('display_interval', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('base_unit', sa.String(length=8), nullable=False),
    sa.Column('n_max', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instruments_serial_number'), 'instruments', ['serial_number'], unique=False)
    op.create_table('test_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('instrument_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'IN_PROGRESS', 'COMPLETED', 'APPROVED', name='sessionstatus', native_enum=False, length=16), nullable=False),
    sa.Column('start_temp_c', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('end_temp_c', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('humidity_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('pressure_hpa', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_sessions_instrument_id'), 'test_sessions', ['instrument_id'], unique=False)
    op.create_table('observations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('test_type', sa.Enum('WEIGHING_PERFORMANCE', 'ECCENTRICITY', 'REPEATABILITY', 'TARE', 'CREEP', 'ZERO_CHECK', name='observationtesttype', native_enum=False, length=32), nullable=False),
    sa.Column('position', sa.String(length=16), nullable=True),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('supersedes_id', sa.Uuid(), nullable=True),
    sa.Column('applied_load', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('indication', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('additional_load', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('zero_error', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('error_prior', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('corrected_error', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('mpe_limit', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('verdict', sa.Enum('PASS', 'FAIL', name='observationverdict', native_enum=False, length=8), nullable=False),
    sa.Column('entered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entered_by', sa.Uuid(), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'SERIAL', 'OCR', name='observationsource', native_enum=False, length=16), nullable=False),
    sa.ForeignKeyConstraint(['entered_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['test_sessions.id'], ),
    sa.ForeignKeyConstraint(['supersedes_id'], ['observations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'test_type', 'position', 'sequence_no', 'revision_no', name='uq_observation_logical_identity')
    )
    op.create_index(op.f('ix_observations_session_id'), 'observations', ['session_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('docx_path', sa.Text(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('qr_payload', sa.Text(), nullable=False),
    sa.Column('signed_by', sa.Uuid(), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('template_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['test_sessions.id'], ),
    sa.ForeignKeyConstraint(['signed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_session_id'), 'reports', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_session_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_observations_session_id'), table_name='observations')
    op.drop_table('observations')
    op.drop_index(op.f('ix_test_sessions_instrument_id'), table_name='test_sessions')
    op.drop_table('test_sessions')
    op.drop_index(op.f('ix_instruments_serial_number'), table_name='instruments')
    op.drop_table('instruments')
    op.drop_index(op.f('ix_audit_log_object_ref'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action_detail'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
