"""add checklist_items table"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '63a3c54cedbc'
down_revision: Union[str, None] = '950e9a084339'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklist_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('clause', sa.String(length=16), nullable=False),
    sa.Column('item_key', sa.String(length=64), nullable=False),
    sa.Column('requirement', sa.Text(), nullable=False),
    sa.Column('test_procedure', sa.String(length=32), nullable=False),
    sa.Column('outcome', sa.Enum('PASSED', 'FAILED', 'UNCHECKED', 'NOT_APPLICABLE', name='checklistoutcome', native_enum=False, length=16), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('supersedes_id', sa.Uuid(), nullable=True),
    sa.Column('entered_by', sa.Uuid(), nullable=False),
    sa.Column('entered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entered_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['test_sessions.id'], ),
    sa.ForeignKeyConstraint(['supersedes_id'], ['checklist_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'clause', 'item_key', 'revision_no', name='uq_checklist_item_revision')
    )
    op.create_index(op.f('ix_checklist_items_session_id'), 'checklist_items', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_checklist_items_session_id'), table_name='checklist_items')
    op.drop_table('checklist_items')
    # ### end Alembic commands ###
