"""add observations second_indication"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '950e9a084339'
down_revision: Union[str, None] = '771edc50b868'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observations', sa.Column('second_indication', sa.Numeric(precision=18, scale=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('observations', 'second_indication')
    # ### end Alembic commands ###
